channels:
  - conda-forge
  - bioconda
dependencies:
  - matplotlib==3.5.0
  - numpy==1.20.3
  - opencv-contrib-python
  - opencv-python
  - opencv-python-headless
  - pandas==1.3.5
  - PhenoGraph
  - Pillow==8.4.0
  - scikit-image
  - scikit-learn
  - scikit-misc
  - seaborn==0.11.2
  - streamlit
  - click==8
